update: 1.创建和集成my_installer自解压安装包构建命令到functions

diff --git a/bin/functions b/bin/functions
--- a/bin/functions
+++ b/bin/functions
@@ -1081,4 +1081,197 @@ function my_deb()
 	fi
 }
 #}}}
+# my_installer{{{
+# 构建install自解压安装包
+# print_template_head{{{
+print_template_head() {
+echo -e '#!/bin/bash
+############################################################################# ##
+# Copyright (C) 2024-2099 ZKLX Optoelectronic Technology Co.LTD
+############################################################################# ##
+#
+# -------------------------------------------------------------------------- --
+#     AUTHOR                   : EExuke
+#     FILE NAME                : my_installer.sh
+#     FILE DESCRIPTION         : 自解压安装包脚本
+#     FIRST CREATION DATE      : 2024/07/30
+# --------------------------------------------------------------------------
+#     Version                  : 1.0
+#     Last Change              : 2024/07/30
+## ************************************************************************** ##
+
+APP_UPGRADE_VER="V'"$1 $2"'"
+ANSI_COLOR_NONE="\\033[0m"
+ANSI_COLOR_RED="\\033[0;31m"
+ANSI_COLOR_LIGHT_RED="\\033[1;31m"
+ANSI_COLOR_GREEN="\\033[0;32m"
+ANSI_COLOR_LIGHT_GREEN="\\033[1;32m"
+ANSI_COLOR_BLUE="\\033[0;34m"
+ANSI_COLOR_LIGHT_BLUE="\\033[1;34m"
+ANSI_COLOR_DARY_GRAY="\\033[1;30m"
+ANSI_COLOR_CYAN="\\033[0;36m"
+ANSI_COLOR_LIGHT_CYAN="\\033[1;36m"
+ANSI_COLOR_PURPLE="\\033[0;35m"
+ANSI_COLOR_LIGHT_PURPLE="\\033[1;35m"
+ANSI_COLOR_BROWN="\\033[0;33m"
+ANSI_COLOR_YELLOW="\\033[1;33m"
+ANSI_COLOR_LIGHT_GRAY="\\033[0;37m"
+ANSI_COLOR_WHITE="\\033[1;37m"
+err() {
+    echo -e ${ANSI_COLOR_RED}"$1"${ANSI_COLOR_NONE}
+}
+warn() {
+    echo -e ${ANSI_COLOR_YELLOW}"$1"${ANSI_COLOR_NONE}
+}
+info() {
+    echo -e ${ANSI_COLOR_GREEN}"$1"${ANSI_COLOR_NONE}
+}
+mvTopath() {
+    info "cp -ar $1/* to $2"
+    chmod 0777 $1/* -R
+    if [[ `sudo cp -ar $1/* $2 > /dev/null 2>&1; echo $?` -ne 0 ]]; then
+        err "!!! cp -ar $1/* to $2 failed! system reboot may fail!!!!CHECK IT!!!"
+        err "!!! please stop services by \"sudo systemctl stop <services>\""
+        return -1
+    fi
+    info "*************cp -ar $1 to $2 success****************"
+}
+
+kill_process() {
+    for file in $1/*
+    do
+        if test -f $file; then
+            sudo killall `basename $file` > /dev/null 2>&1
+        else
+            if test -e $file; then
+                kill_process $file
+            fi
+        fi
+    done
+}
+
+autorun() {
+    TMP_DIR="/tmp/upgrade"
+    TAR_FILE_NAME="${TMP_DIR}/app.tar.gz"
+    UNTAR_DIR="${TMP_DIR}/untar_dir"
+    md5SumMark=""
+    tarOffsetLine=0
+
+    if [[ $# -lt 1 ]]; then
+        err "wrong parameter!!!"
+        return -1
+    fi
+
+    while read line
+    do
+        tarOffsetLine=$(($tarOffsetLine+1))
+        if [[ `expr match "$line" "#md5:"` -ne 0 ]]; then
+            md5SumMark=`echo ${line} | cut -d : -f 2`
+            break
+        fi
+    done < $1
+    tarOffsetLine=$(($tarOffsetLine+1))
+    mkdir -p $TMP_DIR
+    sudo tail -n +$tarOffsetLine $1 > $TAR_FILE_NAME
+    if [[ `md5sum --help > /dev/null 2>&1 && echo 1` -eq 1 ]]; then
+        md5CheckVal=`md5sum $TAR_FILE_NAME | cut -d " " -f1`
+        if [[ $md5SumMark = $md5CheckVal ]]; then
+            info "*****************tar file check OK.....***************"
+        else
+            err "md5check failed: want $md5SumMark but $md5CheckVal, Quit"
+            return -1
+        fi
+    else
+        warn "no md5sum, $TAR_FILE_NAME is possible damaged!"
+    fi
+    info "checking files in tar ......"
+    mkdir -p $UNTAR_DIR
+    if [[ `sudo tar -xzf $TAR_FILE_NAME -C $UNTAR_DIR > /dev/null 2>&1; echo $?` -ne 0 ]]; then
+        err "test untar failed!Quit"
+        return -1
+    fi
+    info "****************test untar files OK......*****************"
+
+    kill_process $UNTAR_DIR
+    mvTopath $UNTAR_DIR/root "/"
+    sync
+
+    return $?
+}
+
+if [[ $# -ge 1 ]]; then
+	echo ${APP_UPGRADE_VER}
+else
+	warn "*****************************************************"
+	warn "*********  应用程序升级中 请勿断电!!!!!!!! **********"
+	warn "*********  应用程序升级中 请勿断电!!!!!!!! **********"
+	warn "*********  应用程序升级中 请勿断电!!!!!!!! **********"
+	warn "*****************************************************"
+	autorun $0
+
+	if [[ $? -eq 0 ]];
+	then
+		echo "upgrade success! reboot device please! after:"
+		echo "do: <depmod>"
+		echo "do: sudo systemctl enable <services>"
+	else
+		echo "upgrade failed, CHECK IT!"
+	fi
+fi
+
+exit'
+}
+#}}}
+function my_installer()
+{
+	if [[ $# < 1 || $# > 3 ]]; then
+		echo -e "${F_GR} Usage: my_installer <src_dir> [install_pack_name] [version] ${F6_END}"
+		return
+	fi
+
+	if [[ $2 == "" ]]; then
+		PACK_NAME=${1%/*}
+	else
+		PACK_NAME=$2
+	fi
+
+	# version info
+	STR_VERSION=v1.0
+	STR_RELEASE=`date "+%Y-%m-%d %H:%M:%S"`
+	if [[ $3 != "" ]]; then
+		STR_VERSION=$3
+	fi
+
+	# target names
+	TAR_FILE=${PACK_NAME}_${STR_VERSION}.tar.gz
+	UPGRADE_FILE=${PACK_NAME}_${STR_VERSION}_installer.sh
+	echo -e "${F_GR} ============================================= ${F6_END}"
+	echo -e "${F_GR} To build ${UPGRADE_FILE} from ${1%/*}/root/ ... ${F6_END} "
+	echo -e "${F_GR} --------------------------------------------- ${F6_END}"
+
+	# tar (*dir must start by "/root/")
+	cd $1
+	if [[ ! -d "root" ]]; then
+		echo -e "${FG_RED} ROOT dir must start by \"root/\" ${F6_END}"
+		echo -e "${FG_RED} Not Found dir: ./root ${F6_END}"
+		return
+	fi
+	tar czf ${TAR_FILE} root/
+
+	# create header
+	print_template_head ${STR_VERSION} ${STR_RELEASE} > ${UPGRADE_FILE}
+
+	# pack tar file
+	echo " " >> ${UPGRADE_FILE}
+	echo "#md5:"`md5sum ${TAR_FILE} | cut -d " " -f 1` >> ${UPGRADE_FILE}
+	cat ${TAR_FILE} >> ${UPGRADE_FILE}
+	rm ${TAR_FILE}
+	chmod +x ${UPGRADE_FILE}
+
+	echo -e "${F_GR} --------------------------------------------- ${F6_END}"
+	echo -e "${F_GR} Build ${UPGRADE_FILE} finished! ${F6_END} "
+	echo -e "${F_GR} ============================================= ${F6_END}"
+}
+#}}}
+
 
